apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: manishkhadria/01-rest-api-hello:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: 01-rest-api-hello
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  type: LoadBalancer
---
#apiVersion: "v1"
#kind: "Service"
#metadata:
#  name: "hello-world-rest-api"
#  namespace: "default"
#  labels:
#    app: "hello-world-rest-api"
#spec:
#  ports:
#  - protocol: "TCP"
#    port: 80
#    targetPort: 8080
#  selector:
#    app: "hello-world-rest-api"
#  type: "ClusterIP"
